
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */
/* do not edit */ import { User } from "./User";
/* do not edit */
/* do not edit */
/* do not edit */   export class Tip {
/* do not edit */     
/* do not edit */     public id: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public date: Date;
/* do not edit */
/* do not edit */     
/* do not edit */     public scoreHomeTeam: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public scoreAwayTeam: number;
/* do not edit */   
/* do not edit */     
/* do not edit */     public matchId: number;
/* do not edit */
/* do not edit */     
/* do not edit */     
/* do not edit */     public createdAt: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public user: User;
/* do not edit */   }
/* do not edit */