
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */
/* do not edit */
/* do not edit */ import { Tip } from "./Tip";
/* do not edit */
/* do not edit */
/* do not edit */
/* do not edit */ export class User {
/* do not edit */   
/* do not edit */   public id: number;
/* do not edit */
/* do not edit */   
/* do not edit */   public username: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public realName: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public grade: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public isAdmin: boolean;
/* do not edit */
/* do not edit */   
/* do not edit */   public isExpert: boolean;
/* do not edit */
/* do not edit */   
/* do not edit */   public expertText: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public expertPosition: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public password: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public tips: Tip[];
/* do not edit */
/* do not edit */   
/* do not edit */   
/* do not edit */   public createdAt: Date;
/* do not edit */
/* do not edit */   public points?: number;
/* do not edit */   public place?: number;
/* do not edit */
/* do not edit */   
/* do not edit */
/* do not edit */   
/* do not edit */ }
/* do not edit */