
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */
/* do not edit */
/* do not edit */ import { Way } from "./Way";
/* do not edit */
/* do not edit */
/* do not edit */
/* do not edit */ export class User {
/* do not edit */   
/* do not edit */   public id: number;
/* do not edit */
/* do not edit */   
/* do not edit */   public username: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public realName: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public grade: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public isAdmin: boolean;
/* do not edit */
/* do not edit */   
/* do not edit */   public password: string;
/* do not edit */
/* do not edit */   
/* do not edit */   public ways: Way[];
/* do not edit */
/* do not edit */   
/* do not edit */   
/* do not edit */   public createdAt: Date;
/* do not edit */
/* do not edit */   
/* do not edit */
/* do not edit */   
/* do not edit */ }
/* do not edit */