
/*    +-----------------------------------------------------------------------+    */
/*    |    Do not edit this file directly.                                    |    */
/*    |    It was copied by redundancyJS.                                     |    */
/*    |    To modify it, first edit the source file (see redundancy.json).    |    */
/*    |    Then, run "npx redundancyjs" in the terminal.                      |    */
/*    +-----------------------------------------------------------------------+    */

/* do not edit */
/* do not edit */ import { User } from "./User";
/* do not edit */
/* do not edit */
/* do not edit */   export class Way {
/* do not edit */     
/* do not edit */     public id: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public date: Date;
/* do not edit */
/* do not edit */     
/* do not edit */     public distance: number;
/* do not edit */
/* do not edit */     
/* do not edit */     public type: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public hidden: boolean;
/* do not edit */
/* do not edit */     
/* do not edit */     public roundIdx: number;
/* do not edit */
/* do not edit */     
/* do not edit */     
/* do not edit */     public createdAt: string;
/* do not edit */
/* do not edit */     
/* do not edit */     public user: User;
/* do not edit */   }
/* do not edit */